### ISSUE TITLE
genotypes file to hdf5 is not available in newer versions

### ISSUE THREAD

**Issue by IvanPrzOl** [cropgeeks/flapjack#28]
How can I convert a .txt into a .hdf5 file using the command line in the new version of flapjack?

**Comment by imilne** [comment]
You can't anymore because that functionality has been removed from Flapjack and migrated into Germinate's codebase (https://github.com/germinateplatform/germinate/blob/d195ac15161b48845d400805304b399c401f9b38/src/jhi/germinate/server/util/FJTabbedToHdf5Converter.java).

If you install a version of Flapjack older than Oct 2018 then it'll still be available: you can find older versions at: http://bioinf.hutton.ac.uk/flapjack/installers/archive/
